"""Identity metadata for experimental data, stored as TOML.

Metadata is the "identity document" of a dataset: it records *what* the
data is (name, uuid, creation time), *where it came from* (instrument,
experiment, operator), *what the files contain* (format, sampling rate,
channels), and *what has been done to it* (an append-only processing
log). Every processing stage applied to the data must be recorded with
`log_stage` so that any derived result remains traceable to its origin.

Schema (``schema_version = 1``)::

    schema_version = 1

    [id]
    uuid = "..."            # RFC 4122 UUID, generated by create_meta
    name = "run-001"
    created_at = "2026-07-20T08:00:00+00:00"   # ISO 8601, UTC

    [source]
    instrument = ""
    experiment = ""
    operator = ""
    description = ""

    [data]
    files = ["run-001.csv"]
    format = "csv"
    fs = 1000.0             # sampling frequency in Hz, must be > 0
    n_samples = 100000
    t_start = 0.0
    t_end = 100.0

    [[data.channels]]
    name = "ch1"
    unit = "V"
    quantity = "voltage"

    [[processing]]
    stage = "lowpass"
    tool = "precision_physkit.filters.lowpass"
    tool_version = "0.1.0"
    params = { cutoff = 50.0, order = 4 }
    at = "2026-07-20T08:05:00+00:00"
    outputs = ["run-001-lowpass.csv"]

Reading uses the standard-library `tomllib`. Writing uses a minimal
built-in serializer (no third-party TOML writer) that supports exactly
the types of this schema: strings, integers, floats, booleans, arrays of
scalars, tables, arrays of tables, and inline tables. Timestamps are
stored as ISO 8601 *strings* (quoted), not TOML datetimes, so a
load/save round-trip preserves types exactly. Optional fields whose
value is None are omitted from the TOML document.
"""

from __future__ import annotations

import math
import re
import tomllib
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

__all__ = [
    "SCHEMA_VERSION",
    "create_meta",
    "load_meta",
    "log_stage",
    "save_meta",
    "validate_meta",
]

SCHEMA_VERSION = 1
"""Metadata schema version written by `create_meta`."""

_BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")

_TOP_LEVEL_KEYS = {"schema_version", "id", "source", "data", "processing"}


def _utc_now_iso() -> str:
    """Return the current UTC time as an ISO 8601 string."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def create_meta(
    name: str,
    *,
    instrument: str = "",
    experiment: str = "",
    operator: str = "",
    description: str = "",
    files: list[str] | None = None,
    format: str = "csv",
    fs: float | None = None,
    n_samples: int | None = None,
    t_start: float | None = None,
    t_end: float | None = None,
    channels: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Create a new metadata document (schema version 1).

    A fresh UUID and the current UTC creation time are generated
    automatically. The processing log starts empty; append to it with
    `log_stage`.

    Parameters
    ----------
    name : str
        Human-readable dataset name. Must be non-empty.
    instrument, experiment, operator, description : str, optional
        Provenance fields of the ``[source]`` section. Empty strings are
        allowed but should be filled in for real data.
    files : list of str, optional
        Data file names belonging to this dataset. Default is an empty
        list.
    format : str, optional
        Data file format tag (e.g. ``"csv"``, ``"npy"``, ``"hdf5"``).
        Default is ``"csv"``. Must be non-empty.
    fs : float, optional
        Sampling frequency in Hz. If given, must be > 0. None means
        "unknown" and omits the field from the TOML document.
    n_samples : int, optional
        Number of samples per channel. If given, must be >= 0.
    t_start, t_end : float, optional
        Time range covered by the data in seconds. If both are given,
        must satisfy ``t_end >= t_start``.
    channels : list of dict, optional
        Channel descriptions; each dict must contain a non-empty
        ``"name"`` and may contain ``"unit"`` and ``"quantity"``
        (defaulting to empty strings), e.g.
        ``{"name": "ch1", "unit": "V", "quantity": "voltage"}``.

    Returns
    -------
    dict
        The metadata document as a nested dict, ready for
        `validate_meta` and `save_meta`.

    Raises
    ------
    ValueError
        If any provided field violates the schema constraints listed
        above.
    TypeError
        If ``channels`` entries are not dicts.

    Examples
    --------
    >>> meta = create_meta("run-001", instrument="scope", fs=1000.0,
    ...                    channels=[{"name": "ch1", "unit": "V", "quantity": "voltage"}])
    >>> validate_meta(meta)
    []
    """
    if not name:
        raise ValueError("name must be a non-empty string.")
    if not format:
        raise ValueError("format must be a non-empty string.")
    if fs is not None and fs <= 0:
        raise ValueError(f"fs must be > 0, got {fs}.")
    if n_samples is not None and n_samples < 0:
        raise ValueError(f"n_samples must be >= 0, got {n_samples}.")
    if t_start is not None and t_end is not None and t_end < t_start:
        raise ValueError(f"t_end ({t_end}) must be >= t_start ({t_start}).")

    channel_list = []
    for ch in channels or []:
        if not isinstance(ch, dict):
            raise TypeError(f"channels entries must be dicts, got {type(ch).__name__}.")
        if not ch.get("name"):
            raise ValueError("each channel must have a non-empty 'name'.")
        channel_list.append(
            {
                "name": str(ch["name"]),
                "unit": str(ch.get("unit", "")),
                "quantity": str(ch.get("quantity", "")),
            }
        )

    return {
        "schema_version": SCHEMA_VERSION,
        "id": {
            "uuid": str(uuid.uuid4()),
            "name": str(name),
            "created_at": _utc_now_iso(),
        },
        "source": {
            "instrument": str(instrument),
            "experiment": str(experiment),
            "operator": str(operator),
            "description": str(description),
        },
        "data": {
            "files": [str(f) for f in files] if files else [],
            "format": str(format),
            "fs": None if fs is None else float(fs),
            "n_samples": None if n_samples is None else int(n_samples),
            "t_start": None if t_start is None else float(t_start),
            "t_end": None if t_end is None else float(t_end),
            "channels": channel_list,
        },
        "processing": [],
    }


def validate_meta(d: dict[str, Any]) -> list[str]:
    """Validate a metadata document against schema version 1.

    Parameters
    ----------
    d : dict
        Metadata document as returned by `create_meta`, `load_meta`, or
        `log_stage`.

    Returns
    -------
    list of str
        Human-readable problem descriptions, one per issue found, in the
        form ``"<field path>: <problem>"``. An empty list means the
        document is valid.

    Examples
    --------
    >>> meta = create_meta("run-001")
    >>> meta["data"]["fs"] = -1.0
    >>> validate_meta(meta)
    ['data.fs: must be > 0, got -1.0']
    """
    problems: list[str] = []

    def require_str(section: dict, key: str, path: str, allow_empty: bool = True) -> None:
        value = section.get(key)
        if not isinstance(value, str):
            problems.append(f"{path}: must be a string, got {type(value).__name__}")
        elif not allow_empty and not value:
            problems.append(f"{path}: must be a non-empty string")

    if not isinstance(d, dict):
        return [f"document: must be a dict, got {type(d).__name__}"]

    for key in d:
        if key not in _TOP_LEVEL_KEYS:
            problems.append(f"{key}: unexpected top-level key")

    version = d.get("schema_version")
    if not isinstance(version, int) or isinstance(version, bool):
        problems.append("schema_version: must be an integer")
    elif version != SCHEMA_VERSION:
        problems.append(
            f"schema_version: unsupported version {version}, expected {SCHEMA_VERSION}"
        )

    id_ = d.get("id")
    if not isinstance(id_, dict):
        problems.append("id: missing or not a table")
    else:
        uuid_str = id_.get("uuid")
        if not isinstance(uuid_str, str) or not uuid_str:
            problems.append("id.uuid: must be a non-empty string")
        else:
            try:
                uuid.UUID(uuid_str)
            except ValueError:
                problems.append(f"id.uuid: not a valid UUID: {uuid_str!r}")
        require_str(id_, "name", "id.name", allow_empty=False)
        created = id_.get("created_at")
        if not isinstance(created, str):
            problems.append("id.created_at: must be an ISO 8601 string")
        else:
            try:
                datetime.fromisoformat(created)
            except ValueError:
                problems.append(f"id.created_at: not ISO 8601: {created!r}")

    source = d.get("source")
    if not isinstance(source, dict):
        problems.append("source: missing or not a table")
    else:
        for key in ("instrument", "experiment", "operator", "description"):
            require_str(source, key, f"source.{key}")

    data = d.get("data")
    if not isinstance(data, dict):
        problems.append("data: missing or not a table")
    else:
        files = data.get("files")
        if not isinstance(files, list) or not all(isinstance(f, str) for f in files):
            problems.append("data.files: must be a list of strings")
        require_str(data, "format", "data.format", allow_empty=False)
        fs = data.get("fs")
        if fs is not None:
            if not isinstance(fs, (int, float)) or isinstance(fs, bool):
                problems.append(f"data.fs: must be a number, got {type(fs).__name__}")
            elif fs <= 0:
                problems.append(f"data.fs: must be > 0, got {fs}")
        n_samples = data.get("n_samples")
        if n_samples is not None:
            if not isinstance(n_samples, int) or isinstance(n_samples, bool):
                problems.append(
                    f"data.n_samples: must be an integer, got {type(n_samples).__name__}"
                )
            elif n_samples < 0:
                problems.append(f"data.n_samples: must be >= 0, got {n_samples}")
        t_start, t_end = data.get("t_start"), data.get("t_end")
        for key, value in (("t_start", t_start), ("t_end", t_end)):
            if value is not None and (
                not isinstance(value, (int, float)) or isinstance(value, bool)
            ):
                problems.append(f"data.{key}: must be a number, got {type(value).__name__}")
        if (
            isinstance(t_start, (int, float))
            and not isinstance(t_start, bool)
            and isinstance(t_end, (int, float))
            and not isinstance(t_end, bool)
            and t_end < t_start
        ):
            problems.append(f"data.t_end: must be >= t_start ({t_end} < {t_start})")
        channels = data.get("channels")
        if channels is None:
            problems.append("data.channels: missing (use an empty array if unknown)")
        elif not isinstance(channels, list):
            problems.append("data.channels: must be an array of tables")
        else:
            for i, ch in enumerate(channels):
                if not isinstance(ch, dict):
                    problems.append(
                        f"data.channels[{i}]: must be a table, got {type(ch).__name__}"
                    )
                    continue
                require_str(ch, "name", f"data.channels[{i}].name", allow_empty=False)
                require_str(ch, "unit", f"data.channels[{i}].unit")
                require_str(ch, "quantity", f"data.channels[{i}].quantity")

    processing = d.get("processing")
    if not isinstance(processing, list):
        problems.append("processing: missing or not an array")
    else:
        for i, entry in enumerate(processing):
            path = f"processing[{i}]"
            if not isinstance(entry, dict):
                problems.append(f"{path}: must be a table, got {type(entry).__name__}")
                continue
            require_str(entry, "stage", f"{path}.stage", allow_empty=False)
            require_str(entry, "tool", f"{path}.tool")
            require_str(entry, "tool_version", f"{path}.tool_version")
            if not isinstance(entry.get("params"), dict):
                problems.append(f"{path}.params: must be a (possibly empty) table")
            at = entry.get("at")
            if not isinstance(at, str):
                problems.append(f"{path}.at: must be an ISO 8601 string")
            else:
                try:
                    datetime.fromisoformat(at)
                except ValueError:
                    problems.append(f"{path}.at: not ISO 8601: {at!r}")
            outputs = entry.get("outputs")
            if not isinstance(outputs, list) or not all(
                isinstance(o, str) for o in outputs
            ):
                problems.append(f"{path}.outputs: must be a list of strings")

    return problems


# ---------------------------------------------------------------------------
# Minimal TOML serializer (supports exactly the types of this schema)
# ---------------------------------------------------------------------------


def _format_key(key: str) -> str:
    """Format a TOML key, quoting it when it is not a bare key."""
    if _BARE_KEY.fullmatch(key):
        return key
    return _format_string(key)


def _format_string(s: str) -> str:
    """Format a string as a TOML basic string with escaping."""
    parts: list[str] = []
    for ch in s:
        code = ord(ch)
        if ch == "\\":
            parts.append("\\\\")
        elif ch == '"':
            parts.append('\\"')
        elif ch == "\n":
            parts.append("\\n")
        elif ch == "\t":
            parts.append("\\t")
        elif ch == "\r":
            parts.append("\\r")
        elif ch == "\b":
            parts.append("\\b")
        elif ch == "\f":
            parts.append("\\f")
        elif code < 0x20 or code == 0x7F:
            parts.append(f"\\u{code:04X}")
        else:
            parts.append(ch)
    return '"' + "".join(parts) + '"'


def _format_scalar(value: Any) -> str:
    """Format a scalar TOML value (str/int/float/bool)."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if math.isnan(value):
            return "nan"
        if math.isinf(value):
            return "inf" if value > 0 else "-inf"
        text = repr(value)
        if "." not in text and "e" not in text and "E" not in text:
            text += ".0"
        return text
    if isinstance(value, str):
        return _format_string(value)
    raise TypeError(f"unsupported TOML value type: {type(value).__name__}")


def _format_inline(value: Any) -> str:
    """Format a value for inline use (array element or inline table)."""
    if isinstance(value, dict):
        items = ", ".join(
            f"{_format_key(k)} = {_format_inline(v)}"
            for k, v in value.items()
            if v is not None
        )
        return "{ " + items + " }" if items else "{}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_format_inline(v) for v in value) + "]"
    return _format_scalar(value)


def _is_table_array(value: Any) -> bool:
    """Return True for a non-empty list consisting only of dicts."""
    return (
        isinstance(value, list)
        and len(value) > 0
        and all(isinstance(item, dict) for item in value)
    )


def _dotted(prefix: list[str]) -> str:
    return ".".join(_format_key(part) for part in prefix)


def _emit_table(lines: list[str], prefix: list[str], table: dict[str, Any]) -> None:
    """Emit one TOML table (header plus content) into ``lines``."""
    scalars: list[tuple[str, Any]] = []
    subtables: list[tuple[str, dict]] = []
    table_arrays: list[tuple[str, list]] = []
    for key, value in table.items():
        if value is None:
            continue  # None means "field omitted"; TOML has no null.
        if isinstance(value, dict):
            subtables.append((key, value))
        elif _is_table_array(value):
            table_arrays.append((key, value))
        else:
            scalars.append((key, value))

    if prefix:
        lines.append(f"[{_dotted(prefix)}]")
    for key, value in scalars:
        lines.append(f"{_format_key(key)} = {_format_inline(value)}")
    if scalars or prefix:
        lines.append("")

    for key, subtable in subtables:
        _emit_table(lines, [*prefix, key], subtable)
    for key, items in table_arrays:
        for item in items:
            lines.append(f"[[{_dotted([*prefix, key])}]]")
            for item_key, item_value in item.items():
                if item_value is None:
                    continue
                if _is_table_array(item_value):
                    raise TypeError(
                        "nested arrays of tables are not supported by this serializer"
                    )
                lines.append(f"{_format_key(item_key)} = {_format_inline(item_value)}")
            lines.append("")


def _dumps(document: dict[str, Any]) -> str:
    """Serialize a metadata document to a TOML string."""
    lines: list[str] = []
    _emit_table(lines, [], document)
    return "\n".join(lines).rstrip("\n") + "\n"


def save_meta(d: dict[str, Any], path: str | Path) -> None:
    """Validate and write a metadata document to a TOML file.

    Parameters
    ----------
    d : dict
        Metadata document. It is validated with `validate_meta` first;
        invalid documents are never written.
    path : str or pathlib.Path
        Destination file (overwritten if it exists), encoded as UTF-8.

    Raises
    ------
    ValueError
        If `validate_meta` reports any problem; the message lists all
        issues.
    TypeError
        If the document contains a value type the built-in TOML
        serializer does not support.

    Examples
    --------
    >>> import tempfile, os
    >>> meta = create_meta("run-001")
    >>> with tempfile.TemporaryDirectory() as tmp:
    ...     path = os.path.join(tmp, "run-001.meta.toml")
    ...     save_meta(meta, path)
    ...     loaded = load_meta(path)
    >>> loaded["id"]["name"]
    'run-001'
    """
    problems = validate_meta(d)
    if problems:
        raise ValueError(
            "invalid metadata document, refusing to save:\n"
            + "\n".join(f"  - {p}" for p in problems)
        )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_dumps(d))


def load_meta(path: str | Path) -> dict[str, Any]:
    """Load and validate a metadata TOML file.

    Parameters
    ----------
    path : str or pathlib.Path
        Path to a ``.toml`` metadata file.

    Returns
    -------
    dict
        The metadata document as a nested dict.

    Raises
    ------
    FileNotFoundError
        If ``path`` does not exist.
    tomllib.TOMLDecodeError
        If the file is not valid TOML.
    ValueError
        If the parsed document fails `validate_meta`; the message lists
        all issues.

    Examples
    --------
    See `save_meta`.
    """
    with open(path, "rb") as fh:
        document = tomllib.load(fh)
    problems = validate_meta(document)
    if problems:
        raise ValueError(
            f"invalid metadata document in {path}:\n"
            + "\n".join(f"  - {p}" for p in problems)
        )
    return document


def _check_inlineable(value: Any, path: str) -> None:
    """Reject param values the TOML serializer cannot represent."""
    if value is None or isinstance(value, (bool, int, float, str)):
        return
    if isinstance(value, dict):
        for key, item in value.items():
            _check_inlineable(item, f"{path}.{key}")
        return
    if isinstance(value, (list, tuple)):
        for i, item in enumerate(value):
            _check_inlineable(item, f"{path}[{i}]")
        return
    raise TypeError(
        f"params{path}: unsupported type {type(value).__name__}; "
        "use str, int, float, bool, or lists/dicts of those"
    )


def log_stage(
    path_or_dict: str | Path | dict[str, Any],
    stage: str,
    tool: str,
    tool_version: str,
    params: dict[str, Any] | None = None,
    outputs: list[str] | None = None,
) -> dict[str, Any]:
    """Append a processing-stage record to a metadata document.

    Every processing stage applied to the data (filtering, resampling,
    fitting, export, ...) must be logged with this function so the
    provenance chain stays complete. The ``at`` timestamp is filled with
    the current UTC time automatically.

    Parameters
    ----------
    path_or_dict : str, pathlib.Path, or dict
        Either the path of a metadata TOML file (loaded, updated, and
        written back atomically-in-content by `save_meta`), or a metadata
        dict, which is updated in place.
    stage : str
        Short name of the processing stage, e.g. ``"lowpass"`` or
        ``"downsample"``. Must be non-empty.
    tool : str
        Function or tool that performed the stage, e.g.
        ``"precision_physkit.filters.lowpass"``.
    tool_version : str
        Version of the tool, e.g. ``precision_physkit.__version__``.
    params : dict, optional
        Stage parameters. Keys and values must be representable in TOML:
        strings, numbers, booleans, or nested lists/dicts thereof. Stored
        as an inline table. Default is an empty table.
    outputs : list of str, optional
        Files produced by this stage. Default is an empty list.

    Returns
    -------
    dict
        The updated metadata document.

    Raises
    ------
    ValueError
        If ``stage`` is empty, or (for a path) if the file fails to load
        or the updated document fails validation.
    TypeError
        If ``path_or_dict`` has an unsupported type or ``params``
        contains values that cannot be serialized to TOML.

    Examples
    --------
    >>> meta = create_meta("run-001")
    >>> meta = log_stage(meta, "lowpass", "precision_physkit.filters.lowpass", "0.1.0",
    ...                  params={"cutoff": 50.0}, outputs=["run-001-lp.csv"])
    >>> meta["processing"][0]["stage"]
    'lowpass'
    """
    if not stage:
        raise ValueError("stage must be a non-empty string.")
    params = dict(params) if params else {}
    _check_inlineable(params, "")

    entry = {
        "stage": str(stage),
        "tool": str(tool),
        "tool_version": str(tool_version),
        "params": params,
        "at": _utc_now_iso(),
        "outputs": [str(o) for o in outputs] if outputs else [],
    }

    if isinstance(path_or_dict, (str, Path)):
        document = load_meta(path_or_dict)
        document["processing"].append(entry)
        save_meta(document, path_or_dict)
        return document
    if isinstance(path_or_dict, dict):
        path_or_dict.setdefault("processing", []).append(entry)
        return path_or_dict
    raise TypeError(
        f"path_or_dict must be a path or a dict, got {type(path_or_dict).__name__}"
    )
